### ISSUE TITLE
Wrong content type uploading svg

### ISSUE THREAD

**Issue by davidino** [sekka1/docker-s3cmd#6]
when it upload svn the content type is `binary/octet-stream` instead of `image`

is there any way to solve this problem ?

**Comment by sekka1** [comment]
Looks like the s3cmd tool does support it (http://s3tools.org/usage | search for `content-type`).  However the way I am executing the s3cmd does not allow for extra params to be added in =(

https://github.com/sekka1/docker-s3cmd/blob/master/files/main.sh#L56

I suppose it can add any docker args as an input parameters.  I would have to test that to make sure it doesnt break anything else.

Or you can try out my other tool which uses the AWS cli S3.  This will list a S3 bucket:  https://github.com/sekka1/aws-cli-docker#return-a-list-of-items-in-s3-bucket

To add in the content type i think you want to do something like this:  http://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

```
docker run \
--env AWS_ACCESS_KEY_ID=<<YOUR_ACCESS_KEY>> \
--env AWS_SECRET_ACCESS_KEY=<<YOUR_SECRET_ACCESS>> \
garland/aws-cli-docker \
aws s3 cp --content-type {my content type} /path/to/local/file s3://mybucket/test2.txt
```

**Comment by davidino** [comment]
Thanks, i solved it with your other docker image `garland/aws-cli-docker`. 

It seems that `s3cmd` is using `python-magic` to guess the file types. I tried to fork you container and add it but without success.
